### PR TITLE
Milestone 4

### PR DESCRIPTION
**Pull request by MarkoNS1990**
In this milestone we are deploying our app to Heroku

### CODE REVIEW

**Comment by mimipeshy** [comment]
## STATUS: CHANGES REQUESTED 🔴 ♻️ 
Hello there @MarkoNS1990 and @mgunduz1 👋🏾 👋🏾 congratulations on making it this far in this milestone

#### Highlights

- You have merged a PR from the development branch to the master branch 
- Good effort in the commit messages

#### To Improve

- [ ] Kindly update your README file to make it professional with all necessary information added
- [ ] Add a link to Heroku in the README file 
- [ ] Ensure that the link to the deployed app is working with all changes made by in previous milestones incorcoprated

That's all 😄, kindly submit another review when done
If you need any clarification, kindly post your comment here and tag me @mimipeshy and will be glad to help

Regards,
Peris Ndanu

**Review by umairarshadbutt — COMMENTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @MarkoNS1990 and @mgunduz1 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed.

##

I have explored your repository. It is a remarkable project you made :+1: ! Awesome README :100: . Kindly work on the suggested changes  👇.
- [ ] README file is updated in the `master` branch, please update it in the `development` branch. Because when a reviewer review a pull request it review it according to git-flow. so please update the live link and other changes in the `develpment` branch. 

##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad (Code Reviewer)](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Review by mke2111 — COMMENTED** [review]
# STATUS: CHANGES REQUIRED 🔴 ♻️ 

## Hey Happy Coder, 👋🏽 
**This is a great project you have going on, well-done lads and thanks for implementing the changes requested earlier on**. 


**However, there are a few sections to improve before your project is approved.** 🔴 
<hr>

### REQUIRED

- [ ] Your live link app redirects to this page.
Screenshot from 2021-05-17 12-27-54


- Ensure that the development branch is up to date with all the implemented features for your app.
- Read on how to push a feature branch to heroku alongside the master branch. Will be something like `git push heroku development:master`


#

### Kindly make all the requested changes and submit another CRR. 💯 

**Cheers 🍹 and Happy coding 💻** 

<hr>

Mention @mke2111 in this thread and I'll be glad to help. 😄 
### Best regards
Slack 🆘  Roy Mukuye
Twitter 🐦  [Roy Mukuye](https://twitter.com/Roymkenya)
LinkedIn 🔗  [Roy Mukuye](https://www.linkedin.com/in/roy-mukuye/)

**Review by umairarshadbutt — COMMENTED** [review]
# **Status: PROJECT APPROVED** :champagne:
Excellent job on this project guys. :fireworks: Keep it up.
##
- All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.
- Congratulations on the splendid job @MarkoNS1990 and @mgunduz1 ! :+1: 
- You can now merge to master and submit the project completion form :rocket: . I wish you all the very best in your next tasks :1st_place_medal:
##
HAPPY CODING :computer:
**[Umair Arshad (Code Reviewer)](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Pull request merged**
